// Major Arcana. astro = Golden Dawn attribution, heb = Hebrew letter.
window.TAROT = window.TAROT || {};
TAROT.majors = [
  { name: "The Fool", astro: "Air", heb: "Aleph א",
    up: ["beginnings", "trust", "a leap"], rv: ["recklessness", "hesitation", "false starts"],
    u: "A new chapter starts with a step you can't fully plan. Travel light, stay curious, and trust that you'll learn the path by walking it.",
    r: "Either you're about to jump without looking, or you've stood at the edge too long. Check the ground, then decide." },
  { name: "The Magician", astro: "Mercury", heb: "Beth ב",
    up: ["will", "skill", "focus"], rv: ["scattered energy", "trickery", "untapped talent"],
    u: "Everything you need is already on the table. Name what you want, focus, and act. Right now intention turns into results.",
    r: "Your tools are idle or pointed the wrong way. Watch for tricks, including the ones you play on yourself, and gather your focus first." },
  { name: "The High Priestess", astro: "Moon", heb: "Gimel ג",
    up: ["intuition", "the unseen", "inner knowing"], rv: ["secrets", "disconnection", "noise"],
    u: "The answer isn't on the surface yet. Be still, listen to what you already sense, and let hidden things come forward in their own time.",
    r: "You're talking over your own inner voice, or something is being kept from you. Turn down the outside noise and ask what you'd rather not know." },
  { name: "The Empress", astro: "Venus", heb: "Daleth ד",
    up: ["abundance", "nurture", "creativity"], rv: ["dependence", "creative block", "neglect"],
    u: "Growth comes from care, not force. Feed what you love, enjoy your senses, and let things ripen: a project, a body, a relationship.",
    r: "You're giving too much away, or nothing is being fed. Turn some of that care back toward yourself before you try to grow anything else." },
  { name: "The Emperor", astro: "Aries", heb: "Heh ה",
    up: ["structure", "authority", "stability"], rv: ["control", "rigidity", "chaos"],
    u: "Order is what's needed. Set the rules, take responsibility, and build the frame that lets everything else stand.",
    r: "Structure has hardened into control, or it's missing entirely. Ask who holds the power here and whether it's used well." },
  { name: "The Hierophant", astro: "Taurus", heb: "Vav ו",
    up: ["tradition", "teaching", "belonging"], rv: ["rebellion", "dogma", "your own path"],
    u: "There's wisdom in the established way. Learn from a teacher, a tradition or a community before you go it alone.",
    r: "The old rules no longer fit. Question what you inherited and find the path that is actually yours." },
  { name: "The Lovers", astro: "Gemini", heb: "Zayin ז",
    up: ["union", "choice", "shared values"], rv: ["imbalance", "misalignment", "avoiding a choice"],
    u: "A bond, or a choice that defines you. Choose with your heart and your values together. What you commit to now shapes who you become.",
    r: "Something is out of tune: between two people, or between what you want and what you believe. Name the conflict honestly." },
  { name: "The Chariot", astro: "Cancer", heb: "Cheth ח",
    up: ["willpower", "direction", "victory"], rv: ["lost direction", "aggression", "being pulled apart"],
    u: "Two forces pull different ways and your will holds the reins. Commit to a direction and drive. Momentum is on your side.",
    r: "You're being pulled apart, or pushing too hard. Stop, re-center, and decide where you're going before you speed up." },
  { name: "Strength", astro: "Leo", heb: "Teth ט",
    up: ["courage", "patience", "gentle power"], rv: ["self-doubt", "raw impulse", "burnout"],
    u: "Real strength is calm. Meet fear and impulse with patience and kindness, and they'll follow you instead of fighting you.",
    r: "Doubt or anger is running the show. Go gentler on yourself. You have more courage than you're using." },
  { name: "The Hermit", astro: "Virgo", heb: "Yod י",
    up: ["solitude", "reflection", "inner light"], rv: ["isolation", "withdrawal", "refusing counsel"],
    u: "Step back from the crowd to hear yourself think. The light you need is the one you carry, and time alone will show you the next step.",
    r: "Solitude has turned into isolation, or you can't sit in the quiet long enough to learn from it. Reach out, or finally slow down." },
  { name: "Wheel of Fortune", astro: "Jupiter", heb: "Kaph כ",
    up: ["cycles", "change", "a turning point"], rv: ["repeating loops", "resistance", "bad timing"],
    u: "The wheel is turning. Circumstances shift whether you're ready or not. Ride the change and look for the pattern behind it.",
    r: "You're caught in a loop, or fighting a turn you can't stop. Notice what keeps repeating. That's where the lesson is." },
  { name: "Justice", astro: "Libra", heb: "Lamed ל",
    up: ["truth", "fairness", "cause and effect"], rv: ["dishonesty", "imbalance", "dodging accountability"],
    u: "Things will be weighed fairly. Be honest, own your part, and expect the consequences you've earned.",
    r: "Something is unfair or unexamined. Look at where you're avoiding the truth, or where you're being judged unjustly." },
  { name: "The Hanged Man", astro: "Water", heb: "Mem מ",
    up: ["surrender", "pause", "a new angle"], rv: ["stalling", "pointless sacrifice", "resistance"],
    u: "Stop pushing. The situation asks you to hang still and see it upside down. What looks like delay is a change of view.",
    r: "You're stuck in limbo or sacrificing for nothing. Either let go for real, or move." },
  { name: "Death", astro: "Scorpio", heb: "Nun נ",
    up: ["endings", "transformation", "clearing"], rv: ["clinging", "stagnation", "fear of change"],
    u: "Something is ending so something else can begin. Let the old form go cleanly. This is transformation, not disaster.",
    r: "You're holding on to what is already over. The ending will come anyway, and resisting it only drags it out." },
  { name: "Temperance", astro: "Sagittarius", heb: "Samekh ס",
    up: ["balance", "moderation", "blending"], rv: ["excess", "imbalance", "impatience"],
    u: "Mix opposites slowly and in the right measure. Patience will produce something better than either extreme.",
    r: "Too much of one thing, too little of another. Recalibrate, and stop rushing something that needs time." },
  { name: "The Devil", astro: "Capricorn", heb: "Ayin ע",
    up: ["attachment", "temptation", "the shadow"], rv: ["release", "breaking free", "facing the shadow"],
    u: "Look at what has a hold on you: a habit, a desire, a fear. The chains are looser than they look. You're freer than you think.",
    r: "A spell is breaking. You see the trap clearly now, and you can step out of it." },
  { name: "The Tower", astro: "Mars", heb: "Peh פ",
    up: ["upheaval", "revelation", "the false collapses"], rv: ["averted disaster", "fear of change", "delayed collapse"],
    u: "A structure built on a false foundation comes down, fast. It's a shock, and it clears the ground for something truer. Break the glass.",
    r: "You're bracing against a collapse that may be necessary, or a crisis was narrowly avoided. Ask what you're propping up." },
  { name: "The Star", astro: "Aquarius", heb: "Tzaddi צ",
    up: ["hope", "healing", "renewal"], rv: ["discouragement", "lost faith", "disconnection"],
    u: "After the storm, a clear sky. Healing is underway. Trust the future and let yourself be open and generous again.",
    r: "Hope has dimmed. Small acts of faith will relight it, so find one thing that's still worth believing in." },
  { name: "The Moon", astro: "Pisces", heb: "Qoph ק",
    up: ["illusion", "dreams", "the unconscious"], rv: ["fog lifting", "fear released", "truth surfacing"],
    u: "Not everything is what it seems. Move carefully through the uncertainty. Your dreams and instincts know more than your eyes do.",
    r: "The fog is lifting. Fears lose their shape, and what was hidden starts to show itself." },
  { name: "The Sun", astro: "Sun", heb: "Resh ר",
    up: ["joy", "success", "vitality"], rv: ["clouded joy", "delay", "overconfidence"],
    u: "Clarity, warmth and success. Things are as good as they look. Enjoy it and let yourself be seen.",
    r: "The light is there, only clouded. Joy may be late or muted. Don't mistake a grey day for a dark one." },
  { name: "Judgement", astro: "Fire", heb: "Shin ש",
    up: ["awakening", "reckoning", "a calling"], rv: ["self-doubt", "ignoring the call", "harsh self-judgement"],
    u: "A wake-up call. Review the past honestly, forgive it, and rise into a new version of yourself.",
    r: "You're judging yourself too harshly, or pretending not to hear the call. The invitation still stands." },
  { name: "The World", astro: "Saturn", heb: "Tav ת",
    up: ["completion", "integration", "wholeness"], rv: ["loose ends", "delay", "no closure"],
    u: "A cycle is complete and everything comes together. Celebrate, then step through the door into the next one.",
    r: "You're nearly there, but something is unfinished. Close the loop before you start the next journey." }
];
