// Minor Arcana. Pips 2–10 carry their Golden Dawn decan; ranks run Ace … King.
window.TAROT = window.TAROT || {};
TAROT.ranks = ["Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Page", "Knight", "Queen", "King"];
TAROT.suits = [
  { id: "wands", name: "Wands", element: "fire", theme: "drive, ambition and creative will" },
  { id: "cups", name: "Cups", element: "water", theme: "feelings, relationships and intuition" },
  { id: "swords", name: "Swords", element: "air", theme: "thought, conflict and hard truths" },
  { id: "pentacles", name: "Pentacles", element: "earth", theme: "money, work, the body and practical matters" }
];
// [astro, upright keywords, reversed keywords, upright meaning, reversed meaning]
TAROT.minors = {
  wands: [
    ["Root of fire", ["spark", "inspiration", "a new venture"], ["delay", "no drive", "false start"], "A spark of inspiration or a new venture. The energy is raw and ready, so act while it's hot.", "The spark is there but won't catch. Something is delaying the start, or the passion is missing."],
    ["Mars in Aries", ["planning", "decisions", "vision"], ["fear of the unknown", "indecision", "playing safe"], "You hold the world in your hand and a choice of direction. Plan boldly; the next move is yours.", "You're staying where it's comfortable. Fear of the unknown is shrinking your plans."],
    ["Sun in Aries", ["expansion", "foresight", "momentum"], ["setbacks", "delays", "thinking small"], "Your ships are going out. Early efforts are paying off, so look further ahead and expand.", "Plans hit delays, or you're thinking too small. Adjust your expectations and keep the long view."],
    ["Venus in Aries", ["celebration", "home", "a milestone"], ["shaky foundations", "tension at home", "postponed joy"], "Time to celebrate something you built: a home, a milestone, a homecoming. Enjoy the stability.", "The celebration is shaky or postponed. Look at what's unsettled underneath."],
    ["Saturn in Leo", ["competition", "friction", "clashing egos"], ["avoided conflict", "truce", "inner tension"], "Everyone is swinging at once. Channel the friction into growth instead of chaos.", "The fighting is ending, or you're dodging a conflict that needs to happen."],
    ["Jupiter in Leo", ["victory", "recognition", "confidence"], ["self-doubt", "fall from grace", "private success"], "A win, and people notice. Accept the recognition gracefully. You earned it.", "Success feels hollow or the applause hasn't come. Don't hang your worth on the crowd."],
    ["Mars in Leo", ["standing firm", "perseverance", "defense"], ["exhaustion", "giving up", "overwhelm"], "You have the high ground. Defend your position with conviction; you can hold it.", "You're worn down by constant defending. Decide which fights are worth it."],
    ["Mercury in Sagittarius", ["speed", "movement", "news"], ["delays", "frustration", "waiting"], "Things move fast now: news, travel, momentum. Act quickly and keep up.", "Momentum stalls. Messages cross or arrive late, and patience is the only speed."],
    ["Moon in Sagittarius", ["resilience", "persistence", "a last stand"], ["fatigue", "paranoia", "giving in"], "Wounded but still standing. One more push; your resilience will carry you through.", "You're running on empty and guarding against threats that may never come. Rest is not surrender."],
    ["Saturn in Sagittarius", ["burden", "responsibility", "hard work"], ["release", "delegation", "strain"], "You're carrying too much. The goal is in sight, but ask what you can put down.", "Something has to give. Delegate or drop a burden before it drops you."],
    ["Earth of fire", ["enthusiasm", "discovery", "a free spirit"], ["impatience", "no direction", "unfocused ideas"], "An eager, curious energy: news of an adventure, or the urge to explore. Follow the spark.", "Lots of ideas, little follow-through. Slow down enough to pick one."],
    ["Air of fire", ["action", "adventure", "passion"], ["haste", "recklessness", "scattered energy"], "Charge forward. Bold action and a hunger for adventure carry the day.", "All speed, no direction. Impulse could burn the bridge you're riding over."],
    ["Water of fire", ["confidence", "warmth", "determination"], ["jealousy", "insecurity", "demands"], "Magnetic confidence and warmth. Own your space; your courage lights others up.", "Self-doubt shows up as jealousy or control. Reconnect with what makes you shine."],
    ["Fire of fire", ["vision", "leadership", "boldness"], ["impulsiveness", "domination", "impossible standards"], "A visionary who turns ideas into movements. Take charge and set the direction.", "Leadership slides into domination or impatience. A vision needs other people to carry it."]
  ],
  cups: [
    ["Root of water", ["new love", "an open heart", "intuition"], ["blocked feelings", "emptiness", "repression"], "Your cup overflows: new love, compassion or a creative opening. Let yourself feel it.", "Feelings are bottled up or the well feels dry. Make room before you expect to be filled."],
    ["Venus in Cancer", ["partnership", "attraction", "connection"], ["imbalance", "miscommunication", "separation"], "A meeting of equals. Mutual respect and attraction, a bond where both people are seen.", "The exchange is uneven. Talk about what isn't being given or received."],
    ["Mercury in Cancer", ["friendship", "celebration", "community"], ["overindulgence", "gossip", "feeling left out"], "Raise a glass with your people. Friendship, celebration and shared joy.", "The party has soured: too much, too loud, or someone's left out. Check your circle."],
    ["Moon in Cancer", ["apathy", "contemplation", "a missed offer"], ["renewed interest", "acceptance", "waking up"], "Bored, withdrawn, looking inward. Notice the offer being held out before you wave it away.", "You're coming out of a slump and ready to say yes to something again."],
    ["Mars in Scorpio", ["loss", "regret", "grief"], ["acceptance", "moving on", "forgiveness"], "Something spilled and you're mourning it. Grieve honestly, then turn around: two cups are still standing.", "You're ready to forgive, let the past be past, and pick up what remains."],
    ["Sun in Scorpio", ["nostalgia", "innocence", "memories"], ["living in the past", "rose-tinted views", "growing up"], "Sweet memories, childhood, an old friend. The kindness of the past has something to teach you.", "Nostalgia becomes a trap if you live there. Honor the past and come back to now."],
    ["Venus in Scorpio", ["choices", "fantasy", "illusion"], ["clarity", "decision", "a reality check"], "Too many options, and not all of them are real. Separate the daydreams from what you can actually have.", "The illusions fade and the real choice becomes clear."],
    ["Saturn in Pisces", ["walking away", "searching deeper", "disillusion"], ["fear of leaving", "drifting", "staying too long"], "Leaving what no longer fulfils you, even if it looks fine from outside. You're after something deeper.", "You know it's time to go but you're afraid to. Or you keep leaving without knowing what you want."],
    ["Jupiter in Pisces", ["contentment", "wishes granted", "satisfaction"], ["smugness", "still wanting", "excess"], "The wish card. What you hoped for is within reach. Enjoy it.", "You got what you wanted and it isn't enough. Ask what you were really wishing for."],
    ["Mars in Pisces", ["harmony", "family", "lasting happiness"], ["a strained home", "clashing values", "disconnection"], "Emotional fulfilment and harmony at home. Love that lasts, and a sense of belonging.", "The picture-perfect version is cracking. Real harmony needs honest repair."],
    ["Earth of water", ["a creative spark", "an intuitive message", "tenderness"], ["moodiness", "creative block", "insecurity"], "A surprise from the heart: an idea, an invitation, a soft new feeling. Stay open to it.", "Feelings are raw and easily hurt. Don't dismiss the dreamy part of you; ground it."],
    ["Air of water", ["romance", "charm", "following the heart"], ["moodiness", "unreal ideals", "empty promises"], "A romantic offer or a heartfelt mission. Follow your feelings with grace.", "Charm without substance. Watch for promises that are all mood and no follow-through."],
    ["Water of water", ["compassion", "emotional security", "intuition"], ["martyrdom", "codependence", "overwhelm"], "Deep empathy held steady. Trust your intuition and care for others without drowning.", "You're soaking up everyone's feelings. Set boundaries so compassion doesn't become self-loss."],
    ["Fire of water", ["emotional balance", "diplomacy", "calm"], ["manipulation", "volatility", "coldness"], "Calm in rough water. Lead with emotional maturity: steady feelings, wise counsel.", "Feelings are suppressed or used as leverage. Composure shouldn't mean coldness."]
  ],
  swords: [
    ["Root of air", ["clarity", "breakthrough", "truth"], ["confusion", "misinformation", "clouded judgement"], "A clear, sharp idea cuts through the fog. Speak the truth plainly; a breakthrough is here.", "The thinking is muddled or the message misread. Get the facts before you strike."],
    ["Moon in Libra", ["stalemate", "a hard choice", "avoidance"], ["indecision", "overload", "the deadlock breaks"], "Blindfolded, swords crossed, refusing to choose. Take off the blindfold and look.", "The stalemate breaks, or the pressure to choose becomes too much to hold."],
    ["Saturn in Libra", ["heartbreak", "grief", "a painful truth"], ["recovery", "forgiveness", "releasing pain"], "A painful truth pierces the heart. Let it hurt. The grief is clean and it will pass.", "The wound is healing. Release the pain instead of replaying it."],
    ["Jupiter in Libra", ["rest", "recovery", "contemplation"], ["restlessness", "burnout", "a forced pause"], "Lay the sword down and rest. Recovery is part of the work.", "You've been running without stopping. Rest now, or your body will insist."],
    ["Venus in Aquarius", ["conflict", "a costly win", "tension"], ["reconciliation", "regret", "moving past it"], "A fight won at too high a price. Ask whether being right is worth what it costs.", "The dust settles. Make peace where you can and let the rest go."],
    ["Mercury in Aquarius", ["transition", "moving on", "calmer water"], ["resistance", "unfinished business", "baggage"], "Moving away from trouble toward calmer water. The crossing is quiet but necessary.", "You can't move on while carrying everything with you. What needs to stay behind?"],
    ["Moon in Aquarius", ["strategy", "stealth", "deception"], ["confession", "conscience", "getting caught"], "Someone is acting alone and in secret. Be strategic, and watch for deception, yours or another's.", "Secrets come out. Come clean, or catch what's being hidden."],
    ["Jupiter in Gemini", ["feeling trapped", "restriction", "limiting beliefs"], ["release", "a new view", "freedom"], "Bound and blindfolded by your own thoughts. The trap is mostly in the mind, and you can walk out.", "You see the way out. Old beliefs about your limits loosen their grip."],
    ["Mars in Gemini", ["anxiety", "nightmares", "worry"], ["hope", "reaching out", "the worst is over"], "Sleepless worry. The fear is real, but it's bigger in the dark than it will be at dawn.", "The anxiety begins to lift. Talk to someone; the worst is behind you."],
    ["Sun in Gemini", ["a painful ending", "rock bottom", "betrayal"], ["recovery", "regeneration", "survival"], "It's over, and it hurts. Rock bottom has one gift: the only way left is up.", "You survived it. Recovery is slow but real, so don't reopen the wound."],
    ["Earth of air", ["curiosity", "new ideas", "vigilance"], ["gossip", "deception", "all talk"], "Quick-minded and watchful. Ask questions, learn fast, stay alert.", "Sharp words without wisdom. Watch for gossip, or ideas that never become action."],
    ["Air of air", ["ambition", "fast thinking", "drive"], ["impulsiveness", "aggression", "no plan"], "Charging in with ideas and arguments. Act decisively; truth is on the move.", "Rushing in with words as weapons. Think before you charge."],
    ["Water of air", ["clear boundaries", "independence", "honest perception"], ["coldness", "bitterness", "cruelty"], "Clear-eyed and direct. Speak honestly, set boundaries, and trust your judgement.", "Honesty has sharpened into coldness. Old wounds may be talking for you."],
    ["Fire of air", ["intellect", "authority", "truth"], ["manipulation", "abuse of power", "rigid thinking"], "Clear reasoning and fair judgement. Lead with the mind, and lead ethically.", "Intellect used to dominate or deceive. Logic without heart turns cruel."]
  ],
  pentacles: [
    ["Root of earth", ["opportunity", "prosperity", "a solid start"], ["a missed chance", "poor planning", "scarcity"], "A seed of real, tangible opportunity: money, work, health. Plant it carefully.", "An opportunity slips away, or the plan has no foundation. Look before you invest."],
    ["Jupiter in Capricorn", ["balance", "adaptability", "juggling"], ["overcommitment", "disorder", "dropped balls"], "Juggling priorities with a light touch. Stay flexible; the balance keeps moving.", "Too many balls in the air and something is about to drop. Prioritize."],
    ["Mars in Capricorn", ["teamwork", "craft", "learning"], ["disharmony", "sloppy work", "going solo"], "Skilled work done together. Collaborate, learn from people who know, and take pride in the craft.", "The team isn't pulling together, or quality is slipping. Fix the process."],
    ["Sun in Capricorn", ["security", "saving", "control"], ["greed", "possessiveness", "letting go"], "Holding on to what you have. Security is good; make sure it isn't becoming a cage.", "You're gripping too tightly, or learning to loosen your hold. Generosity may be the safer bet."],
    ["Mercury in Taurus", ["hardship", "loss", "being left out in the cold"], ["recovery", "help arriving", "the worst easing"], "Hard times, out in the cold. Help is closer than it feels; look for the lit window.", "The worst of the hardship is easing. Accept the help that's offered."],
    ["Moon in Taurus", ["generosity", "giving and receiving", "fairness"], ["strings attached", "debt", "one-sided giving"], "Giving and receiving in fair measure. Share what you have, or accept help gracefully.", "Help with strings attached. Watch the power in who gives and who takes."],
    ["Saturn in Taurus", ["patience", "the long view", "investment"], ["impatience", "poor returns", "wasted effort"], "The crop is growing but not ready. Check your investment and keep tending it.", "Effort without reward. Change the strategy, or give it more time?"],
    ["Sun in Virgo", ["mastery", "diligence", "skill"], ["perfectionism", "lost focus", "cut corners"], "Head down, honing your craft. Repetition and care build mastery.", "Either obsessing over details or rushing the work. Find a pace you can keep."],
    ["Venus in Virgo", ["independence", "comfort", "self-sufficiency"], ["overwork", "appearances", "a setback"], "Enjoying the fruit of your own labor: self-reliant, comfortable, refined.", "Security built on overwork, or looks over substance. What is it all for?"],
    ["Mercury in Virgo", ["legacy", "wealth", "family"], ["money troubles", "family conflict", "short-term thinking"], "Lasting wealth and legacy. Build something that outlives you.", "Money and family get tangled. Look at what you're actually leaving behind."],
    ["Earth of earth", ["study", "ambition", "a new skill"], ["procrastination", "no progress", "daydreaming"], "A student with a practical dream. Learn the skill and take the first concrete step.", "Plans that never leave the notebook. Start small, but start."],
    ["Air of earth", ["diligence", "routine", "reliability"], ["stagnation", "boredom", "inertia"], "Slow, steady, dependable. Progress comes through consistent effort.", "Stuck in a rut. Routine has turned into inertia."],
    ["Water of earth", ["nurture", "practicality", "abundance"], ["self-neglect", "work–home imbalance", "smothering"], "Warm, practical care. Look after body, home and money with grounded wisdom.", "You care for everything except yourself. Rebalance work and home."],
    ["Fire of earth", ["abundance", "security", "discipline"], ["greed", "stubbornness", "materialism"], "Wealth built and managed well. Steady leadership and generous success.", "Success measured only in money. Don't let security turn into control."]
  ]
};
